### PR TITLE
Use ezs-lodex statements instead of local statements

### PR DESCRIPTION
**Pull request by parmentf**

### CODE REVIEW

**Comment by touv** [comment]
@parmentf  Can I merge this PR ?

**Comment by parmentf** [comment]
@touv No you can't. I forgot to put the label.
It will take some time...

**Comment by parmentf** [comment]
We get time outs from Travis (on e2e tests).

**Comment by parmentf** [comment]
I don't understand why tests don't pass on Travis.
Since aea2290.

**Comment by parmentf** [comment]
- [x] I should rewrite `exportExtendedNquads` with an ezs statement (after all, it's simpler than a sub-pipe).
- [x] I should also remove old statements (as `scroll,` and `extractIstexQuery).`
- [x] I should remove the `ezs-basics` module from `exportExtendedNquadsCompressed.js`
- [x] I should check the old (more than one year) pull request about writing exportExtendedNquads tests (#463), to use the ones already written.

**Review by touv — APPROVED** [review]

**Comment by parmentf** [comment]
Oh. This PR should fix extended NQuads exports (at least big exports, as the scroll duration has been increased).

**Review by Kmaschta — APPROVED** [review]

**Pull request merged**
