### PR TITLE
[RFR] Fix proxy

### PR DESCRIPTION
**Pull request by parmentf**
Maybe `.env` is not required (I did not tried without it, and I don't know how many caches there are, where they are, and how to reset them).

The proxy environment variables need to be taken into account at building.

### CODE REVIEW

**Comment by parmentf** [comment]
I did not test either without the docker-compose v2 syntax (headers in `docker-compose.yml`.
I don't know if it's critical for the rest of docker process.

**Review by djhi — COMMENTED** [review]
Where is `.env` used ? Is it automatically loaded by docker or docker-compose ?

**Comment by parmentf** [comment]
Not sure `.env` is used. But it could be used by [docker-compose](https://docs.docker.com/compose/env-file/).

**Comment by djhi** [comment]
Then it would be nice to document how to use it in the README. Maybe inside a new  *Troubleshooting* section ?

**Comment by parmentf** [comment]
Yep. And I realize we added specific values in `.env`.

I should delete `lodex_server` image, rename `.env`, and launch `make docker-run-dev` again to see if docker-compose really needs `.env` or not.

**Comment by parmentf** [comment]
OK. It's not useful.

**Comment by djhi** [comment]
Forgot to mention it before but environment variables should be in uppercase. If you don't mind about this convention, just say so and I'll merge this pr

**Comment by parmentf** [comment]
They ARE in lowercase in `docker-compose.yml` (and were before I went).

**Comment by parmentf** [comment]
But I guess it would work in uppercase too: I define both cases in my bash.
In fact, [inist-tools](https://github.com/Inist-CNRS/inist-tools) do it for me.

**Comment by parmentf** [comment]
I talked to @touv and we prefer to _add_ uppercase variables, without discarding lowercase ones.

That's because some softwares take into account one case, and others take only the other case.

**Pull request merged**
