### PR TITLE
[RFR] add favicon

### PR DESCRIPTION
**Pull request by touv**

### CODE REVIEW

**Comment by parmentf** [comment]
Oh? You change the LODEX logo to the semantic web logo?

**Comment by touv** [comment]
I didn't found the lodex logo with favicon format, do you have it  ?
If you have, you can replace this file with yours.

**Comment by parmentf** [comment]
I got it in .png. https://github.com/istex/istex-lodex-data/blob/master/favicon.png

**Comment by parmentf** [comment]
But yes, I found them in the LODEX Project drive.

**Comment by touv** [comment]
great, you can merge

**Pull request merged**
