### PR TITLE
New format streamgraph

### PR DESCRIPTION
**Pull request by youlot**
This pr include some updates relative to the admin part and the border line on an hover.

### CODE REVIEW

**Comment by Kmaschta** [comment]
Because you re-opened an existing branch, you are not up-to-date from master.
Please rebase.

**Comment by youlot** [comment]
The rebase is done :)

**Comment by Kmaschta** [comment]
Seeing the number of commits, it's clearly not rebased, also all the commits from the previous branch are still there.

Did you pull master before the rebase?

**Comment by youlot** [comment]
hmm yes.. I did a pull from master, move to this branch and did a rebase -i master by selecting the last commit I wanted

**Comment by Kmaschta** [comment]
How did you rebased without push-force?

**Comment by youlot** [comment]
just commited and push after the rebase..

**Pull request closed without merging**
