### PR TITLE
Add the max value parameter in admin panel

### PR DESCRIPTION
**Pull request by youlot**

### CODE REVIEW

**Review by touv — CHANGES_REQUESTED** [review]
Why don't you use the RoutineParamsAdmin component ?
You can use it like the other graphs. It's more consistent.
https://github.com/Inist-CNRS/lodex/blob/b43989d1bee8f7bf7d307fe0e905a10c90e8f725/src/app/js/formats/network/NetworkAdmin.js#L71-L75


https://github.com/Inist-CNRS/lodex/blob/master/src/app/js/formats/network/NetworkAdmin.js#L71-L75

**Comment by youlot** [comment]
Because on the Hierarchy graph we don't need the minValue, maxValue, orderBy parameters.

**Comment by touv** [comment]
I think this function is  is useless : 
```
    setMaxSize = (_, maxSizeValue) => {
        this.setParams({ maxSize: maxSizeValue });
    };
```

**Comment by youlot** [comment]
Yes, that was a mistake

**Review by touv — APPROVED** [review]

**Pull request merged**
