### PR TITLE
Feat: disable auto close on error toast

### PR DESCRIPTION
**Pull request by thibault-barrat**
https://user-images.githubusercontent.com/41492953/218154638-ff26c14c-d4fb-4490-8df6-8e0b02da1af9.mov

### CODE REVIEW

**Review by arimet — APPROVED** [review]
I approve, but the demand is only for error ? 
Because the code could be simpler if we do the same for all notification

**Comment by thibault-barrat** [comment]
> I approve, but the demand is only for error ? Because the code could be simpler if we do the same for all notification

Yes, the demand is only for error. That's why I modified each toast and not the container

**Comment by floo51** [comment]
Can we proxy react-toastify with a function that calls it with the right arguments depending on error type? Code would be a lot cleaner

**Comment by thibault-barrat** [comment]
> Can we proxy react-toastify with a function that calls it with the right arguments depending on error type? Code would be a lot cleaner

Smart idea 👍

**Review by floo51 — APPROVED** [review]

**Pull request merged**
