### PR TITLE
Istex summary return

### PR DESCRIPTION
**Pull request by ThieryMichel**
follow #747 
- [x] display count
- [x] display year by decade when more than ten
- [ ] add load more button for document (in next PR)

### CODE REVIEW

**Comment by Kmaschta** [comment]
Rebase needed

**Comment by Kmaschta** [comment]
Rebase needed

**Comment by Kmaschta** [comment]
Rebase needed

**Comment by Kmaschta** [comment]
Rebase needed

**Review by Kmaschta — APPROVED** [review]

**Comment by ThieryMichel** [comment]
it's rebased

**Comment by ThieryMichel** [comment]
it's rebased

**Comment by ThieryMichel** [comment]
it's rebased

**Comment by ThieryMichel** [comment]
it's rebased :trollface:

**Review by Kmaschta — APPROVED** [review]

**Pull request merged**
